name: PR Approval Gate
on:
  workflow_run:
    workflows: [PR Approval Checks]
    types: [completed]
    branches:
      - main
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: exit 1
