name: Bot Approval if Check
on:
  pull_request:
    types: [opened, edited]
    branches: [main]
  pull_request_review:
    types: [submitted]
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approve if Bypass
        env:
          AUTH_HEADER: 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
          JSON_HEADER: 'Content-Type: application/json'
          REVIEWS_URL: 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews'
        if: ${{ contains(github.event.pull_request.body, 'EMERGENCY_SKIP_REVIEW') }}
        run: |
          echo "Bypass Description found"
          curl \
          -X POST \
          -H '${AUTH_HEADER}' \
          -H '${JSON_HEADER}' \
          -d '{"event":"APPROVE"}' \
          "${REVIEWS_URL}"
