name: Bot Approval if Check
on:
  pull_request:
    types: [opened, edited]
    branches: [main]
  pull_request_review:
    types: [submitted]
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approve if Bypass
        if: ${{ contains(github.event.pull_request.body, 'EMERGENCY_SKIP_REVIEW') }}
        run: |
          echo "Bypass Description found"
          curl -sSL -X POST \
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews' \
          -d '{"event":"APPROVED"}'

