name: ci
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
  approval:
    name: PR Approval Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: |
          echo "Repo: $GH_REPO"
          echo "Context: $GITHUB_CONTEXT"
      - name: Print PR
        run: echo '${{ toJSON(github.event.pull_request) }}'
      - name: Fail if not approved
        if: ${{ !contains(github.event.pull_request.bodyText, 'EMERGENCY_SKIP_REVIEW=') && github.event.pull_request.review_decision != 'approved' }}
        run: exit 1
      - name: Fallback test review decision only
        if: ${{ failure() && github.event.pull_request.review_decision == 'approved' }}
        run: exit 0
