name: ci
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
  approval:
    name: PR Approval Gateway
    runs-on: ubuntu-20.04
    steps:
      - name: Print body
        run: echo ${{ github.event.pull_request.comments }}
      - name: Print PR
        run: echo ${{ github.event.pull_request }}
      - name: Print Review
        run: echo ${{ github.event.pull_request.review_decision }}
      - name: Fail if not approved
        if: ${{ !contains(github.event.pull_request.bodyText, 'EMERGENCY_SKIP_REVIEW=') && github.event.pull_request.review_decision != 'approved' }}
        run: exit 1
