name: ci
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
  approval:
    name: PR Approval Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo '${{ toJSON(github.event.pull_request) }}'
      - name: Succeed If Emergency Tag
        if: ${{ contains(github.event.pull_request.body, 'EMERGENCY_SKIP_REVIEW') }}
        run: exit 0
      - name: Succeed If Approved
        if: ${{ failure() && github.event.pull_request.review_decision == 'approved' }}
        run: exit 0
      - name: Fail
        if: ${{ failure() }}
        run: exit 1
