name: ci
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
  approval:
    name: PR Approval Gateway
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: echo '${{ toJSON(github.event.pull_request) }}'
      - name: Print Review
        run: echo '${{ toJSON(github.event.review) }}'
      - name: Fail If No Emergency Tag or Approval
        env:
          AUTH_HEADER: '${{ secrets.GITHUB_TOKEN }}'
          JSON_HEADER: 'Content-Type: application/json'
          REVIEWS_URL: 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews'
        run: |
          reviews=(curl -sSL --request POST -H "${JSON_HEADER}" -H "${AUTH_HEADER}" "${REVIEWS_URL}")
          echo $reviews
