name: ci
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  pull_request_review:
    types: [submitted]
jobs:
  approval:
    name: PR Approval Gateway
    runs-on: ubuntu-20.04
    steps:
      - name: approve
        if: !contains(github.event.pull_request.bodyText, 'EMERGENCY_SKIP_REVIEW') && github.event.pull_request.review_decision != PullRequestReviewDecision.APPROVED
        run: exit 1
