name: PR Approval Bypass Notifier
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Fail If No Emergency Tag or Approval
        env:
          AUTH_HEADER: 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
          JSON_HEADER: 'Content-Type: application/json'
          REVIEWS_URL: 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews'
        run: |
          reviews=$(curl -sSL -H "${JSON_HEADER}" -H "${AUTH_HEADER}" "${REVIEWS_URL}" | jq --raw-output '.[] | @base64')
          declare -A changes_requested_reviews
          declare -A approved_reviews
          for review in $reviews
          do
            review_state=$(echo "$review" | base64 -d | jq --raw-output '.state')
            review_user=$(echo "$review" | base64 -d | jq --raw-output '.user.id')
            if [[ $review_state == "CHANGES_REQUESTED" ]]
            then
              changes_requested_reviews[$review_user]='true'
              unset approved_reviews[$review_user]
            elif [[ $review_state == "APPROVED" ]]
            then
              approved_reviews[$review_user]='true'
              unset changes_requested_reviews[$review_user]
            fi
          done
          if [[ ${#approved_reviews[@]} == 0 || ${#changes_requested_reviews[@]} > 0 ]]
          then
            echo "Pull Request Bypassed Approval"
            exit 1
          fi
      - name: Slack Notification
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_APPROVAL_WEBHOOK }}'
          SLACK_CHANNEL: 'general'
          SLACK_USERNAME: 'naughty_bypass'
          SLACK_ICON: 'https://www.flaticon.com/free-icon/github_2111432'
        uses: rtCamp/action-slack-notify@v2
