name: PR Approval Bypass Notifier
on:
  pull_request:
    types: [closed]
    branches: [main]
permissions:
  pull-requests: read
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Fail Check If No Approval
        if: ${{ github.event.pull_request.merged }}
        env:
          AUTH_HEADER: 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
          JSON_HEADER: 'Content-Type: application/json'
          REVIEWS_URL: 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews'
        run: |
          curl -sSL -H "${JSON_HEADER}" -H "${AUTH_HEADER}" "${REVIEWS_URL}" \
          | jq --exit-code '. | map({user: .user.login, state: .state})
          | reduce .[] as $x ({}; .[$x.user] = $x.state) | to_entries | map(.value)
          | contains(["APPROVED"]) and (contains(["CHANGES_REQUESTED"]) | not)'
      - name: Slack Notification
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_APPROVAL_WEBHOOK }}'
          SLACK_CHANNEL: 'general'
          SLACK_USERNAME: 'naughty_bypass'
          SLACK_ICON: 'https://www.flaticon.com/free-icon/github_2111432'
        uses: rtCamp/action-slack-notify@v2
